name: BuildJS
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Install node
      uses: actions/setup-node@v1
      with:
          node-version: '10.x'

    - name: Setup System
      run: |
        sudo apt-get update
        sudo apt-get install wine64 -y
        sudo apt-get install --no-install-recommends -y libopenjp2-tools
        sudo apt-get install --no-install-recommends -y rpm
        sudo apt-get install --no-install-recommends -y bsdtar
        sudo apt-get install snapcraft --classic
        sudo apt-get install multipass --beta --classic
    
    - name: Check out code
      uses: actions/checkout@v1
    
    - name: Install Yarn
      run: npm install -g yarn

    - name: Install
      run: yarn install --frozen-lockfile

    - name: Build
      run: yarn run dist